CRUD Views Django/CRUD_Views_Django/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import path,include
from app import views

urlpatterns = [
    # Uncomment the next line to enable the admin:
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('app/',include('app.urls',namespace='app'))

]

CRUD Views Django/app/urls.py
from django.conf.urls import url
from django.urls import path
from app import views


app_name = 'app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete')
    ]

CRUD Views Django/app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class school(models.Model):
    name = models.CharField(max_length=128)
    principal = models.CharField(max_length=128)
    location = models.CharField(max_length=128)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("app:detail",kwargs={'pk':self.pk})

class student(models.Model):
    name = models.CharField(max_length=128)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(school,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

CRUD Views Django/app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
#importing the different views
from django.views.generic import (View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.http import HttpResponse
#importing the model
from app import models

# Create your views here.

class IndexView(TemplateView):
    template_name = 'app/index.html'

# list view example
class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.school




# detail view example
class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.school
    template_name = 'app/schooldetails.html'


class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.school


class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.school

class SchoolDeleteView(DeleteView):
    model = models.school
    template_name = 'app/school_confirm_delete.html'
    success_url = reverse_lazy("app:list")

CRUD Views Django/app/templates/app/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'app:list' %}">schools</a></li>
             <li><a class="navbar-link" href="{% url 'admin:index' %}">admin</a></li>
             <li><a class="navbar-link" href=""></a></li>
             <li><a class="navbar-link" href=""></a></li>
        </ul>
    </nav>
    <div class="container">
          {% block body_block %}
    {% endblock %}

    </div>
  

</body>
</html>

CRUD Views Django/app/templates/app/index.html
{% extends "app/base.html" %}
{% block body_block %}
<h1>hello every one</h1>
{% endblock %}

CRUD Views Django/app/templates/app/school_confirm_delete.html
{% extends "app/base.html" %}
{% block body_block %}
<h1>delete{{ school.name }}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="delete"/>
    <a href="{% url 'app:detail' pk=school.pk %}">cancel</a>
</form>
{% endblock %}

CRUD Views Django/app/templates/app/school_form.html
{% extends "app/base.html" %}
{% block body_block %}

<h1>
    {% if not form.instance.pk %}
    create school
    {% else %}
    updte school
    {% endif %}
</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="submit" />

</form>
{% endblock %}

CRUD Views Django/app/templates/app/school_list.html
<!DOCTYPE html>
{% extends "app/base.html" %}

{% block body_block %}
<p><a class="btn btn-warning" href="{% url 'app:create' %}">create</a></p>
<h1>welcome to list of schools</h1>
<ol>
    {% for school in schools %}
    <li><a href="{{ school.id }}"><h2>{{ school.name }}</h2></a></li>
    {% endfor %}
</ol>
{%  endblock %}

CRUD Views Django/app/templates/app/schooldetails.html
<!DOCTYPE html>

{% extends "app/base.html" %}

{% block body_block %}
<div class="jumbotron">
    <h1>welcome to details of schools</h1>
    <h2>school details</h2>
    <p>{{ school_detail.name }}</p>
    <p>{{ school_detail.principal }}</p>
    <p>{{ school_detail.location }}</p>
    <h3>students:</h3>
    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{ student.age}} years old</p>
    {% endfor %}


</div>
<div class="container">
    <p><a class="btn btn-warning" href="{% url 'app:update' pk=school_detail.pk %}">update</a></p>
    <p><a class="btn btn-warning" href="{% url 'app:delete' pk=school_detail.pk %}">delete</a></p>
   

</div>

{%  endblock %}